global:
  message: Welcome to Customer Service Dev Environment!!!
server:
  port: 8082
message: Hello from Customer Dev!!
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: pgadmin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
