global:
  message: Welcome to Order Service Prod Environment!!!
server:
  port: 8085
message: Hello from Order Prod!!
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: pgadmin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
