global:
  message: Welcome to Order Service Dev Environment!!!
server:
  port: 8084
message: Hello from Order Dev!!
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: pgadmin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
